version: '3.9'

services:
  next-application:
    image: node:18
    container_name: nextjs-app
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    command: sh -c "npm install && npm run build && npm start"