// 'use client'

// import { Provider } from 'react-redux';
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
// import store from './store';
import Application from "./application";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Application children={children}/>
        {/* <Provider store={store} >
          <div className="container">
            {children}            
          </div>          
        </Provider> */}
      </body>
    </html>
  );
}
